import { Noto_Sans } from "next/font/google";
import { Header } from "@/components/header";
import "./globals.css";
import { twMerge } from "tailwind-merge";

const noto = Noto_Sans({ subsets: ["latin", "cyrillic"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={twMerge(noto.className, "flex flex-col min-h-screen")}>
        <Header />
        {children}
      </body>
    </html>
  );
}
